add new fucntion in postgres

diff --git a/docker-compose/docker-compose.yml b/docker-compose/docker-compose.yml
--- a/docker-compose/docker-compose.yml
+++ b/docker-compose/docker-compose.yml
@@ -1,5 +1,3 @@
-version: '3.9'
-
 services:
 
   vault:
@@ -27,11 +25,15 @@ services:
     image: busybox
     environment:
       CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
+      CLICKHOUSE_PG_USER_PASSWORD: ${CLICKHOUSE_PG_USER_PASSWORD}
+      POSTGRES_HOST: ${POSTGRES_HOST}
+      POSTGRES_DB: ${POSTGRES_DB}
     volumes:
       - ./vault/ssl/postgres-server:/var/lib/postgresql/certs/
       - ./vault/ssl/postgres-client-keycloak:/var/lib/postgresql-client/certs/
       - ./vault/ssl/clickhouse-server:/work/certs
       - ./clickhouse_config/users.d:/work/users.d
+      - ./postgresConfig/postgres-init:/work/postgres-init
     command: |
       sh -e -c '
         echo "[INIT] Настройка сертификатов..."
@@ -60,24 +62,72 @@ services:
       <networks>
       <ip>::/0</ip>
       </networks>
+      <access_management>1</access_management>
+      <named_collection_control>1</named_collection_control>
+      <show_named_collections>1</show_named_collections>
+      <show_named_collections_secrets>1</show_named_collections_secrets>
       </admin>
       </users>
       </clickhouse>
       EOF
       
       chmod 644 /work/users.d/admin.xml
-      echo "[OK] admin.xml успешно создан:"
-      cat /work/users.d/admin.xml
+      echo "[OK] admin.xml успешно создан"
+
+      echo "[INIT] Генерация schema.sql..."
+      if [ -z "$CLICKHOUSE_PG_USER_PASSWORD" ]; then
+        echo "[ERROR] CLICKHOUSE_PG_USER_PASSWORD не задан!" >&2
+        exit 1
+      fi
+      
+      cat > /work/postgres-init/01_schema.sql <<EOF
+      create schema alerting;
+      CREATE DATABASE keycloak;
+      CREATE EXTENSION IF NOT EXISTS pgcrypto;
+      CREATE EXTENSION IF NOT EXISTS pg_cron;
+      CREATE EXTENSION IF NOT EXISTS plpython3u;
+      CREATE USER clickhouse_user WITH PASSWORD '\''$${CLICKHOUSE_PG_USER_PASSWORD}'\'';
+      GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO clickhouse_user;
+      GRANT USAGE ON SCHEMA public TO clickhouse_user;
+      GRANT SELECT ON ALL TABLES IN SCHEMA public TO clickhouse_user;
+      ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO clickhouse_user;
+      EOF
+      
+      chmod 644 /work/postgres-init/01_schema.sql
+      echo "[OK] schema.sql успешно создан"
+
+      echo "[INIT] Генерация default-user.xml..."
+      cat > /work/users.d/default-user.xml <<EOF
+      <clickhouse>
+        <users>
+          <default remove="remove">
+          </default>
+          
+          <user_ch>
+            <profile>default</profile>
+            <networks>
+              <ip>::/0</ip>
+            </networks>
+            <password><![CDATA[your_ch_password]]></password>
+            <quota>default</quota>
+            <named_collection_control>1</named_collection_control>
+          </user_ch>
+        </users>
+      </clickhouse>
+      EOF
+      
+      chmod 644 /work/users.d/default-user.xml
+      echo "[OK] default-user.xml успешно создан"
       '
     depends_on:
       - postgres
       - clickhouse
+      - init-clickhouse-collections
 
   init-container-ssl:
     image: busybox
     depends_on:
       - init-db-postgres
-      - init-db-clickhouse
       - minio
       - keycloak
       - monitoring-api
@@ -145,15 +195,19 @@ services:
     image: clickhouse/clickhouse-server:25.9.2.1  # лучше закрепить версию, а не :latest
     container_name: clickhouse-bitdive
     environment:
+      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
+      PGSSLMODE: disable
       CLICKHOUSE_USER: ${CLICKHOUSE_USER}
       CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
       CLICKHOUSE_DB: ${CLICKHOUSE_DB}
     volumes:
       - ./clickhouse_config/users.d:/etc/clickhouse-server/users.d:rw
       - ./clickhouse_config/config.d/ssl.xml:/etc/clickhouse-server/config.d/ssl.xml:ro
+      - ./clickhouse_config/config.d/tmp.xml:/etc/clickhouse-server/config.d/tmp.xml:ro
       - ./vault/ssl/clickhouse-server:/etc/clickhouse-server/certs:ro
-      #- ./clickhouse_data:/var/lib/clickhouse
+      - ./clickhouse_data:/var/lib/clickhouse
       - ./clickhouse_logs:/var/log/clickhouse-server
+      - ./clickhouse_tmp:/var/lib/clickhouse/tmp:rw
     networks:
       - flink-network
 
@@ -226,9 +280,36 @@ services:
     networks:
       - flink-network
 
+  init-clickhouse-collections:
+    image: clickhouse/clickhouse-server:25.9.2.1
+    container_name: init-clickhouse-collections
+    environment:
+      CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
+      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
+      CLICKHOUSE_PG_USER_PASSWORD: ${CLICKHOUSE_PG_USER_PASSWORD}
+      POSTGRES_HOST: ${POSTGRES_HOST}
+      POSTGRES_DB: ${POSTGRES_DB}
+    entrypoint: ["/bin/bash", "-c"]
+    command: |
+      "
+        echo '[INIT] Ожидание доступности ClickHouse...'
+        sleep 10
+        until clickhouse-client --host $${CLICKHOUSE_HOST} --port 9000 --user admin --password $${CLICKHOUSE_PASSWORD} --query 'SELECT 1' 2>/dev/null; do
+          echo 'ClickHouse недоступен, ждем...'
+          sleep 3
+        done
+        
+        echo '[INIT] Создание named collection postgres_creds...'
+        clickhouse-client --host $${CLICKHOUSE_HOST} --port 9000 --user admin --password $${CLICKHOUSE_PASSWORD} --query \"CREATE NAMED COLLECTION IF NOT EXISTS postgres_creds AS host = '$${POSTGRES_HOST}', port = 5432, user = 'clickhouse_user', password = '$${CLICKHOUSE_PG_USER_PASSWORD}', database = '$${POSTGRES_DB}'\" && echo '[OK] Named collection создана' || echo '[WARN] Не удалось создать коллекцию'
+      "
+    networks:
+      - flink-network
+
   init-db-postgres:
     image: frolikoveabitdive/bitdive-db-liquibase-postgres:latest
     container_name: bitdive-init-db-postgres
+    depends_on:
+      - init-db-clickhouse
     environment:
       POSTGRES_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
       POSTGRES_USER: ${POSTGRES_USER}
@@ -367,8 +448,6 @@ services:
   mcp-server:
     image: frolikoveabitdive/docker-file-mcp-server:latest
     container_name: mcp-server
-    ports:
-      - "8089:8089"
     environment:
       TOKEN_SECRET: ${TOKEN_SECRET}
       POSTGRES_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
